# Generated by Django 5.2.1 on 2025-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
